# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Display the version of go that we have installed
        run: go version

      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}

      - name: Install Dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: "DEBUG: What's our directory & what's in it?"
        run: pwd && ls

      - name: Build the dev_setup executables
        run: ./build-executables.sh ${{ github.event.release.tag_name }}

      - name: List the dev_setup executables
        run: ls -l ./release

      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref }}
          assets: |
            *.gz
            *.zip

      - name: Upload the dev_setup binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: main
          file: ./release/dev_setup-*
          file_glob: true
          overwrite: true